spring:
  application:
    name: spring-security-authorization-method-level

server:
  error:
    include-stacktrace: never
    include-exception: false

logging:
  level:
    org:
      springframework:
        security: trace
