server.port=9090

server.ssl.key-store=classpath:ssl/serverkeystore.jks
server.ssl.key-alias=tcserver
server.ssl.key-store-type=JKS
server.ssl.key-store-password=topsecret

okta.oauth2.client-id=0oa1ec2wh3xkWhHhN5d7
okta.oauth2.client-secret=3nAypSZjbBU_HQIQRjxV0mRsitG68jmi8bkzXGjr
okta.oauth2.issuer=https://dev-35030395.okta.com/oauth2/default
okta.oauth2.redirect-uri=/authorization-code/callback
okta.oauth2.scopes=openid, profile, email